import "@/assets/css/main.css";
import Footer from "../_Components/_Footer";
import Header from "../_Components/_Header";
import Menu from "../_Components/_Menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
          <Header />
          <div className="app-main">
            <Menu />
            <div className="app-main__outer">
            {children}
            <Footer/>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
